export default [
  {
    categoryId: 163,
    categoryName: 'Health',
    subcategoryId: 236,
    subcategoryName: 'Pharmacy',
  },
  {
    categoryId: 163,
    categoryName: 'Health',
    subcategoryId: 245,
    subcategoryName: 'Health insurance',
  },
  {
    categoryId: 163,
    categoryName: 'Health',
    subcategoryId: 261,
    subcategoryName: 'Doctor',
  },
  {
    categoryId: 163,
    categoryName: 'Health',
    subcategoryId: 268,
    subcategoryName: 'Health - Others',
  },
  {
    categoryId: 163,
    categoryName: 'Health',
    subcategoryId: 322,
    subcategoryName: 'Optician / Eyecare',
  },
  {
    categoryId: 163,
    categoryName: 'Health',
    subcategoryId: 325,
    subcategoryName: 'Dentist',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 90,
    subcategoryName: 'Business services - Others',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 202,
    subcategoryName: 'Advertising',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 203,
    subcategoryName: 'Office services',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 204,
    subcategoryName: 'Shipping',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 205,
    subcategoryName: 'Printing',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 265,
    subcategoryName: 'Business expenses',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 270,
    subcategoryName: 'Online services',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 274,
    subcategoryName: 'Office supplies',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441886,
    subcategoryName: 'Employer contributions',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441889,
    subcategoryName: 'Accounting',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441890,
    subcategoryName: 'Salaries',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441891,
    subcategoryName: 'Salary of executives',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441892,
    subcategoryName: 'Hiring fees',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441895,
    subcategoryName: 'Consulting',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441896,
    subcategoryName: 'Outsourcing',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441897,
    subcategoryName: 'Disability Insurance',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441898,
    subcategoryName: 'Training taxes',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441899,
    subcategoryName: 'Legal Fees',
  },
  {
    categoryId: 166,
    categoryName: 'Business services',
    subcategoryId: 441900,
    subcategoryName: 'Marketing',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 237,
    subcategoryName: 'Education & Children - Others',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 238,
    subcategoryName: 'School supplies',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 239,
    subcategoryName: 'Tuition',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 240,
    subcategoryName: 'Pension',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 241,
    subcategoryName: 'Student housing',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 259,
    subcategoryName: 'Student loan',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 266,
    subcategoryName: 'Toys',
  },
  {
    categoryId: 167,
    categoryName: 'Education & Children',
    subcategoryId: 267,
    subcategoryName: 'Baby-sitter & Daycare',
  },
  {
    categoryId: 159,
    categoryName: 'Taxes',
    subcategoryId: 206,
    subcategoryName: 'Taxes - Others',
  },
  {
    categoryId: 159,
    categoryName: 'Taxes',
    subcategoryId: 207,
    subcategoryName: 'Fine',
  },
  {
    categoryId: 159,
    categoryName: 'Taxes',
    subcategoryId: 208,
    subcategoryName: 'Incomes taxes',
  },
  {
    categoryId: 159,
    categoryName: 'Taxes',
    subcategoryId: 209,
    subcategoryName: 'Property taxes',
  },
  {
    categoryId: 159,
    categoryName: 'Taxes',
    subcategoryId: 302,
    subcategoryName: 'Taxes',
  },
  {
    categoryId: 159,
    categoryName: 'Taxes',
    subcategoryId: 441988,
    subcategoryName: 'VAT',
  },
  {
    categoryId: 160,
    categoryName: 'Misc. expenses',
    subcategoryId: 1,
    subcategoryName: 'Uncategorized',
  },
  {
    categoryId: 160,
    categoryName: 'Misc. expenses',
    subcategoryId: 276,
    subcategoryName: 'Others spending',
  },
  {
    categoryId: 160,
    categoryName: 'Misc. expenses',
    subcategoryId: 278,
    subcategoryName: 'Insurance',
  },
  {
    categoryId: 160,
    categoryName: 'Misc. expenses',
    subcategoryId: 294,
    subcategoryName: 'Charity',
  },
  {
    categoryId: 160,
    categoryName: 'Misc. expenses',
    subcategoryId: 308,
    subcategoryName: 'Tobacco',
  },
  {
    categoryId: 160,
    categoryName: 'Misc. expenses',
    subcategoryId: 324,
    subcategoryName: 'Laundry / Dry cleaning',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 223,
    subcategoryName: 'Entertainment - Others',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 224,
    subcategoryName: 'Pets',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 226,
    subcategoryName: 'Hobbies',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 227,
    subcategoryName: 'Bars & Clubs',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 242,
    subcategoryName: 'Sports',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 244,
    subcategoryName: 'Arts & Amusement',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 249,
    subcategoryName: 'Travels / Vacation',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 263,
    subcategoryName: 'Hotels',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 269,
    subcategoryName: 'Amusements',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 310,
    subcategoryName: 'Winter sports',
  },
  {
    categoryId: 170,
    categoryName: 'Entertainment',
    subcategoryId: 320,
    subcategoryName: 'Eating out',
  },
  {
    categoryId: 164,
    categoryName: 'Bank',
    subcategoryId: 79,
    subcategoryName: 'Banking fees and charges',
  },
  {
    categoryId: 164,
    categoryName: 'Bank',
    subcategoryId: 89,
    subcategoryName: 'Mortgage refund',
  },
  {
    categoryId: 164,
    categoryName: 'Bank',
    subcategoryId: 192,
    subcategoryName: 'Savings',
  },
  {
    categoryId: 164,
    categoryName: 'Bank',
    subcategoryId: 194,
    subcategoryName: 'Mortgage',
  },
  {
    categoryId: 164,
    categoryName: 'Bank',
    subcategoryId: 195,
    subcategoryName: 'Bank - Others',
  },
  {
    categoryId: 164,
    categoryName: 'Bank',
    subcategoryId: 306,
    subcategoryName: 'Banking services',
  },
  {
    categoryId: 164,
    categoryName: 'Bank',
    subcategoryId: 756587,
    subcategoryName: 'Payment incidents',
  },
  {
    categoryId: 168,
    categoryName: 'Food & Dining',
    subcategoryId: 83,
    subcategoryName: 'Restaurants',
  },
  {
    categoryId: 168,
    categoryName: 'Food & Dining',
    subcategoryId: 188,
    subcategoryName: 'Food - Others',
  },
  {
    categoryId: 168,
    categoryName: 'Food & Dining',
    subcategoryId: 260,
    subcategoryName: 'Fast foods',
  },
  {
    categoryId: 168,
    categoryName: 'Food & Dining',
    subcategoryId: 273,
    subcategoryName: 'Supermarkets / Groceries',
  },
  {
    categoryId: 168,
    categoryName: 'Food & Dining',
    subcategoryId: 313,
    subcategoryName: 'Coffee shop',
  },
  {
    categoryId: 171,
    categoryName: 'Bills & Utilities',
    subcategoryId: 180,
    subcategoryName: 'Internet',
  },
  {
    categoryId: 171,
    categoryName: 'Bills & Utilities',
    subcategoryId: 219,
    subcategoryName: 'Cable TV',
  },
  {
    categoryId: 171,
    categoryName: 'Bills & Utilities',
    subcategoryId: 258,
    subcategoryName: 'Home phone',
  },
  {
    categoryId: 171,
    categoryName: 'Bills & Utilities',
    subcategoryId: 277,
    subcategoryName: 'Mobile phone',
  },
  {
    categoryId: 171,
    categoryName: 'Bills & Utilities',
    subcategoryId: 280,
    subcategoryName: 'Subscription - Others',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 183,
    subcategoryName: 'Gifts',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 184,
    subcategoryName: 'High Tech',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 186,
    subcategoryName: 'Shopping - Others',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 243,
    subcategoryName: 'Books',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 262,
    subcategoryName: 'Sporting goods',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 272,
    subcategoryName: 'Clothing & Shoes',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 318,
    subcategoryName: 'Music',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 319,
    subcategoryName: 'Movies',
  },
  {
    categoryId: 162,
    categoryName: 'Shopping',
    subcategoryId: 441888,
    subcategoryName: 'Licences',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 84,
    subcategoryName: 'Auto & Transport - Others',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 87,
    subcategoryName: 'Gas & Fuel',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 196,
    subcategoryName: 'Public transportation',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 197,
    subcategoryName: 'Train ticket',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 198,
    subcategoryName: 'Plane ticket',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 247,
    subcategoryName: 'Auto insurance',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 251,
    subcategoryName: 'Parking',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 264,
    subcategoryName: 'Car rental',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 288,
    subcategoryName: 'Car maintenance',
  },
  {
    categoryId: 165,
    categoryName: 'Auto & Transport',
    subcategoryId: 309,
    subcategoryName: 'Tolls',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 216,
    subcategoryName: 'Rent',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 217,
    subcategoryName: 'Electricity',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 218,
    subcategoryName: 'Gas',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 220,
    subcategoryName: 'Home - Others',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 221,
    subcategoryName: 'Home improvement',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 222,
    subcategoryName: 'Maintenance',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 246,
    subcategoryName: 'Home insurance',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 293,
    subcategoryName: 'Water',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 323,
    subcategoryName: 'Lawn & Garden',
  },
  {
    categoryId: 161,
    categoryName: 'Home',
    subcategoryId: 328,
    subcategoryName: 'Misc. utilities',
  },
  {
    categoryId: 303,
    categoryName: 'Withdrawals, checks & transfer',
    subcategoryId: 78,
    subcategoryName: 'Transfer',
  },
  {
    categoryId: 303,
    categoryName: 'Withdrawals, checks & transfer',
    subcategoryId: 85,
    subcategoryName: 'Withdrawals',
  },
  {
    categoryId: 303,
    categoryName: 'Withdrawals, checks & transfer',
    subcategoryId: 88,
    subcategoryName: 'Checks',
  },
  {
    categoryId: 303,
    categoryName: 'Withdrawals, checks & transfer',
    subcategoryId: 326,
    subcategoryName: 'Internal transfer',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 3,
    subcategoryName: 'Other incomes',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 80,
    subcategoryName: 'Interest incomes',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 230,
    subcategoryName: 'Salaries',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 231,
    subcategoryName: 'Sales',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 232,
    subcategoryName: 'Services',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 233,
    subcategoryName: 'Extra incomes',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 271,
    subcategoryName: 'Deposit',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 279,
    subcategoryName: 'Retirement',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 282,
    subcategoryName: 'Internal transfer',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 283,
    subcategoryName: 'Refunds',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 289,
    subcategoryName: 'Savings',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 314,
    subcategoryName: 'Rent',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 327,
    subcategoryName: 'Pension',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 441893,
    subcategoryName: 'Grants',
  },
  {
    categoryId: 2,
    categoryName: 'Incomes',
    subcategoryId: 441894,
    subcategoryName: 'Loans',
  },
  {
    categoryId: 315,
    categoryName: 'Personal care',
    subcategoryId: 235,
    subcategoryName: 'Hairdresser',
  },
  {
    categoryId: 315,
    categoryName: 'Personal care',
    subcategoryId: 248,
    subcategoryName: 'Cosmetics',
  },
  {
    categoryId: 315,
    categoryName: 'Personal care',
    subcategoryId: 316,
    subcategoryName: 'Spa & Massage',
  },
  {
    categoryId: 315,
    categoryName: 'Personal care',
    subcategoryId: 317,
    subcategoryName: 'Personal care - Others',
  },
  {
    categoryId: 315,
    categoryName: 'Personal care',
    subcategoryId: 321,
    subcategoryName: 'Beauty care',
  },
];
